### ISSUE TITLE
documentSymbol error when opening file

### ISSUE THREAD

**Issue by TheoWinterhalter** [coq-community/vscoq#106]
Every time I open a file I get the following error message:
```
[Error - 10:50:42 AM] Request textDocument/documentSymbol failed.
  Message: Request textDocument/documentSymbol failed unexpectedly without providing any details.
  Code: -32603 
```

**Comment by artagnon** [comment]
I do too, but I think it's normal, because:

1. `coqidetop` doesn't load the whole file on startup, and hence can't possibly provide this information.
2. I don't think `textDocument/documentSymbol` should be advertised in the list of LSP capabilities.

**Comment by awalterschulze** [comment]
I also get the same error:
```
Coq Language Server: process.version: v12.4.0, process.arch: x64}
Loaded project at <...>
Changed path to: /Applications/CoqIDE_8.10.2.app/Contents/Resources/bin
[Error - 3:28:19 PM] Request textDocument/documentSymbol failed.
  Message: Request textDocument/documentSymbol failed unexpectedly without providing any details.
  Code: -32603 
```

**Comment by awalterschulze** [comment]
Switching to `CoqIDE_8.5pl3` fixes this problem, but then I have other problems.

**Comment by awalterschulze** [comment]
Ok, no sorry that was a false negative.  `CoqIDE_8.5pl3` still gives me similar problems:
Given the following input
```
Add LoadPath "/Users/walterschulze/Desktop/Coq/cpdtlib".
Require Import CpdtTactics.

Check (fun x: nat => x).
...
```

I get the following error, which has the same error description and error code, as reported above:
```
...
Call Add("Check (fun x: nat =>...", editId: 0, stateId: 3, verbose: false)
/Users/walterschulze/.vscode/extensions/maximedenes.vscoq-0.3.0/client/server/src/util/AnnotatedText.js:39
    else if (text.substitution) { // TextAnnotation
                  ^

TypeError: Cannot read property 'substitution' of undefined
    at Object.textToDisplayString (/Users/walterschulze/.vscode/extensions/maximedenes.vscoq-0.3.0/client/server/src/util/AnnotatedText.js:39:19)
    at Object.parseError (/Users/walterschulze/.vscode/extensions/maximedenes.vscoq-0.3.0/client/server/src/parsing/error-parsing.js:198:22)
    at CoqStateMachine.onCoqMessage (/Users/walterschulze/.vscode/extensions/maximedenes.vscoq-0.3.0/client/server/src/stm/STM.js:907:108)
    at Object.onMessage (/Users/walterschulze/.vscode/extensions/maximedenes.vscoq-0.3.0/client/server/src/stm/STM.js:106:62)
    at CoqTop.doOnMessage (/Users/walterschulze/.vscode/extensions/maximedenes.vscoq-0.3.0/client/server/src/coqtop/IdeSlave8.js:134:28)
    at Object.onMessage (/Users/walterschulze/.vscode/extensions/maximedenes.vscoq-0.3.0/client/server/src/coqtop/IdeSlave8.js:52:56)
    at XmlStream.<anonymous> (/Users/walterschulze/.vscode/extensions/maximedenes.vscoq-0.3.0/client/server/src/coqtop/xml-protocol/coq-xml.js:32:81)
    at XmlStream.emit (events.js:200:13)
    at XmlStream.onCloseTag (/Users/walterschulze/.vscode/extensions/maximedenes.vscoq-0.3.0/client/server/src/coqtop/xml-protocol/coq-xml.js:120:22)
    at SAXStream.<anonymous> (/Users/walterschulze/.vscode/extensions/maximedenes.vscoq-0.3.0/client/server/src/coqtop/xml-protocol/coq-xml.js:50:52)
[Info  - 3:36:29 PM] Connection to server got closed. Server will restart.
Coq Language Server: process.version: v12.4.0, process.arch: x64}
Loaded project at /Users/walterschulze/Desktop/Coq
Changed path to: /Applications/CoqIDE_8.5pl3.app/Contents/Resources/bin
[Error - 3:36:29 PM] Request textDocument/documentSymbol failed.
  Message: Request textDocument/documentSymbol failed unexpectedly without providing any details.
  Code: -32603 
starting coqtop
exec: /Applications/CoqIDE_8.5pl3.app/Contents/Resources/bin/coqtop -v
```

**Comment by artagnon** [comment]
Can you try vscoq master? (Hit F5 on the vscoq project). There have been a
considerable number of changes, but a release hasn’t been cut yet.

**Comment by awalterschulze** [comment]
I don't understand where I should be hitting F5.
When I go to the extension in VSCode and hit F5, it as me to "Select
Environment".
When I search for vscoq in Extensions button on the left, then there is a
Settings icon, this has an option "Install Another Version..", but only
0.3.0 is available.
Maybe there is another way?

Or why not release a version?

**Comment by awalterschulze** [comment]
Thank you so much for fixing this.
At least I think the release of 0.3.1 fixes this.
I have been playing with it for an hour and things have been working very well :D
Open and Closed VSCode several times and no problems like this one.
Tried Coq 8.5.3 and 8.10.2, and both worked.
There are now some minor other problems, but nothing that I can't work around.
Thank you thank you thank you, this is really amazing :D

**Comment by TheoWinterhalter** [comment]
Indeed it might well be fixed with the latest update.

**Comment by maximedenes** [comment]
> I don't think `textDocument/documentSymbol` should be advertised in the list of LSP capabilities.

Indeed that's the right fix. PR incoming.

I don't know if the symptoms of this issue changed recently, but the underlying problem is still there.
